version: '3.9'

services:
  app:
    build: .
    container_name: adaptive_text
    restart: always
    #    ports:
    #      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017

  redis:
    image: redis:latest # Use the specific version if necessary
    ports:
      - "6379:6379" # Maps Redis port 6379 on Docker to Redis port 6379 on your host
    volumes:
      - redis_data:/data # Persist data across container restarts

volumes:
  redis_data: # Defines a volume named redis_data
  mongo_data: # Defines a volume named mongo_data
